Add mandelbrot
codeplaysoftware/parallelts-range-exploration pull request #9
Opened 2018-01-18 16:11 UTC by tremmelg

Add a test calculating the Mandelbrot set.

2018-01-31 09:21 UTC, Ruyk requested changes
Please, add some comments explaining the implementation

2018-01-31 09:21 UTC, Ruyk commented on examples/tests/mandelbrot.cpp
> +      if (ZiN + ZrN > 4.0f) {
use a constant instead of 4.0 and 2.0 (e.g , radius and then 2*radius)

2018-01-31 09:21 UTC, Ruyk commented on examples/tests/mandelbrot.cpp
> +    return (y * 255) / niters;
why is this multiplied by 255? either comment or constant

2018-01-31 09:21 UTC, Ruyk commented on examples/tests/mandelbrot.cpp
> +    a = 255;
can you explain how this storage works?

2018-01-31 09:21 UTC, Ruyk commented on examples/tests/mandelbrot.cpp
> +  }
Add some documentation about how this class and the operator works

2018-01-31 11:15 UTC, tremmelg commented on examples/tests/mandelbrot.cpp
> +    return (y * 255) / niters;
It was to scale it to be between 0 and 255 as an `unsigned char` grayscale pixel, but I've changed it to use coloured output already.

2018-01-31 12:00 UTC, tremmelg commented on examples/tests/mandelbrot.cpp
> +    a = 255;
It assigns some colours to each pixel but I can't explain how it ends up with these particular colours.
![mandelbrot](https://user-images.githubusercontent.com/3776240/35621992-35829cec-067e-11e8-9fb7-ef968d0c606d.jpeg)

2018-02-05 16:56 UTC, Ruyk approved these changes

2018-02-06 09:02 UTC, merged